In [13]:
from bs4 import BeautifulSoup
import requests
url = BeautifulSoup('https://www.worldometers.info/coronavirus', 'html.parser')
soup = requests.get(url)
soup

C:\ProgramData\Anaconda3\lib\site-packages\bs4\__init__.py:404: MarkupResemblesLocatorWarning: The input looks more like a URL than markup. You may want to use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  warnings.warn(

In [14]:
code = BeautifulSoup(soup.text,"lxml")
code = code.find("table", class_="table table-bordered table-hover main_table_countries")
tr_code = code.find_all("tr")
tr_code

[<tr>
 <th width="1%">#</th>
 <th width="100">Country,<br/>Other</th>
 <th width="20">Total<br/>Cases</th>
 <th width="30">New<br/>Cases</th>
 <th width="30">Total<br/>Deaths</th>
 <th width="30">New<br/>Deaths</th>
 <th width="30">Total<br/>Recovered</th>
 <th width="30">New<br/>Recovered</th>
 <th width="30">Active<br/>Cases</th>
 <th width="30">Serious,<br/>Critical</th>
 <th width="30">TotÂ Cases/<br/>1M pop</th>
 <th width="30">Deaths/<br/>1M pop</th>
 <th width="30">Total<br/>Tests</th>
 <th width="30">Tests/<br/>
 <nobr>1M pop</nobr>
 </th>
 <th width="30">Population</th>
 <th style="display:none" width="30">Continent</th>
 <th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
 <th width="30">New Cases/1M pop</th>
 <th width="30">New Deaths/1M pop</th>
 <th width="30">Active Cases/1M pop</th>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="North America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>North America</nobr>
 </td>
 <td>131,889,132</td>
 <td></td>
 <td>1,695,941</td>
 <td></td>
 <td>127,665,129</td>
 <td>+350</td>
 <td>2,528,062</td>
 <td>6,095</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="North America" style="display:none;">North America</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Asia</nobr>
 </td>
 <td>221,500,265</td>
 <td></td>
 <td>1,553,662</td>
 <td></td>
 <td>205,673,091</td>
 <td></td>
 <td>14,273,512</td>
 <td>14,733</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Asia" style="display:none;">Asia</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Europe</nobr>
 </td>
 <td>253,406,198</td>
 <td></td>
 <td>2,101,824</td>
 <td></td>
 <td>248,754,104</td>
 <td>+474</td>
 <td>2,550,270</td>
 <td>4,453</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Europe" style="display:none;">Europe</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="South America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>South America</nobr>
 </td>
 <td>70,200,879</td>
 <td></td>
 <td>1,367,332</td>
 <td></td>
 <td>66,683,585</td>
 <td></td>
 <td>2,149,962</td>
 <td>8,953</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="South America" style="display:none;">South America</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Oceania</nobr>
 </td>
 <td>14,895,771</td>
 <td></td>
 <td>33,015</td>
 <td></td>
 <td>14,752,388</td>
 <td></td>
 <td>110,368</td>
 <td>31</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Africa</nobr>
 </td>
 <td>12,860,924</td>
 <td></td>
 <td>258,892</td>
 <td></td>
 <td>12,090,808</td>
 <td></td>
 <td>511,224</td>
 <td>529</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Africa" style="display:none;">Africa</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr></nobr>
 </td>
 <td>721</td>
 <td></td>
 <td>15</td>
 <td></td>
 <td>706</td>
 <td></td>
 <td>0</td>
 <td>0</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="" style="display:none;"></td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world">
 <td></td>
 <td style="text-align:left;">World</td>
 <td>704,753,890</td>
 <td>0</td>
 <td>7,010,681</td>
 <td>0</td>
 <td>675,619,811</td>
 <td>+790</td>
 <td>22,123,398</td>
 <td>34,794</td>
 <td>90,413</td>
 <td>899.4</td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="all" style="display:none">All</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
 <td style="font-weight: bold; text-align:right">111,820,082</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">1,219,487                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">109,814,428</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">786,167</td>
 <td style="font-weight: bold; text-align:right">940</td>
 <td style="font-weight: bold; text-align:right">333,985</td>
 <td style="font-weight: bold; text-align:right">3,642</td>
 <td style="font-weight: bold; text-align:right">1,186,851,502</td>
 <td style="font-weight: bold; text-align:right">3,544,901</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,805,269</a> </td>
 <td data-continent="North America" style="display:none">North America</td>
 <!-- 1 Case/Death/Test every X -->
 <td>3</td><td>275</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">2,348</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
 <td style="font-weight: bold; text-align:right">45,035,393</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">533,570                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right;">N/A</td>
 <td style="text-align:right;font-weight:bold;">N/A</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">32,016</td>
 <td style="font-weight: bold; text-align:right">379</td>
 <td style="font-weight: bold; text-align:right">935,879,495</td>
 <td style="font-weight: bold; text-align:right">665,334</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,406,631,776</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>31</td><td>2,636</td><td>2</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">0.4</td>
 </tr>,
 <tr style="background-color:#F0F0F0">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
 <td style="font-weight: bold; text-align:right">40,138,560</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">167,642                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">39,970,918</span></td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">612,013</td>
 <td style="font-weight: bold; text-align:right">2,556</td>
 <td style="font-weight: bold; text-align:right">271,490,188</td>
 <td style="font-weight: bold; text-align:right">4,139,547</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,584,518</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>391</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
 <td style="font-weight: bold; text-align:right">38,828,995</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">183,027                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">38,240,600</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">405,368</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">462,891</td>
 <td style="font-weight: bold; text-align:right">2,182</td>
 <td style="font-weight: bold; text-align:right">122,332,384</td>
 <td style="font-weight: bold; text-align:right">1,458,359</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,883,596</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>458</td><td>1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">4,833</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
 <td style="font-weight: bold; text-align:right">38,743,918</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">711,380                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">36,249,161</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">1,783,377</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">179,908</td>
 <td style="font-weight: bold; text-align:right">3,303</td>
 <td style="font-weight: bold; text-align:right">63,776,166</td>
 <td style="font-weight: bold; text-align:right">296,146</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,353,593</a> </td>
 <td data-continent="South America" style="display:none">South America</td>
 <!-- 1 Case/Death/Test every X -->
 <td>6</td><td>303</td><td>3</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">8,281</td>
 </tr>,
 <tr style="background-color:#F0F0F0">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>
 <td style="font-weight: bold; text-align:right">34,571,873</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">35,934                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">34,535,939</span></td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">673,523</td>
 <td style="font-weight: bold; text-align:right">700</td>
 <td style="font-weight: bold; text-align:right">15,804,065</td>
 <td style="font-weight: bold; text-align:right">307,892</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/south-korea-population/">51,329,899</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>1</td><td>1,428</td><td>3</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/japan/">Japan</a></td>
 <td style="font-weight: bold; text-align:right">33,803,572</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">74,694                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right;">N/A</td>
 <td style="text-align:right;font-weight:bold;">N/A</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">269,169</td>
 <td style="font-weight: bold; text-align:right">595</td>
 <td style="font-weight: bold; text-align:right">100,414,883</td>
 <td style="font-weight: bold; text-align:right">799,578</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/japan-population/">125,584,838</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>4</td><td>1,681</td><td>1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">95,582</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
 <td style="font-weight: bold; text-align:right">26,723,249</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">196,487                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">26,361,218</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">165,544</td>
 <td style="font-weight: bold; text-align:right">22</td>
 <td style="font-weight: bold; text-align:right">443,445</td>
 <td style="font-weight: bold; text-align:right">3,261</td>
 <td style="font-weight: bold; text-align:right">281,126,449</td>
 <td style="font-weight: bold; text-align:right">4,665,010</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,262,770</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>307</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">2,747</td>
 </tr>,
 <tr style="background-color:#F0F0F0">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
 <td style="font-weight: bold; text-align:right">24,910,387</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">232,112                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">24,678,275</span></td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">0</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">363,666</td>
 <td style="font-weight: bold; text-align:right">3,389</td>
 <td style="font-weight: bold; text-align:right">522,526,476</td>
 <td style="font-weight: bold; text-align:right">7,628,357</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,497,907</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>3</td><td>295</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
 <td style="font-weight: bold; text-align:right">24,124,215</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">402,756                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">23,545,818</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">175,641</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">165,454</td>
 <td style="font-weight: bold; text-align:right">2,762</td>
 <td style="font-weight: bold; text-align:right">273,400,000</td>
 <td style="font-weight: bold; text-align:right">1,875,095</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,805,947</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>6</td><td>362</td><td>1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>

In [15]:
rows = []
for i in tr_code[1:]:
    tds = []
    for j in i:
        z = j.text.replace(" ","").replace('\n','')
        if z != "":
            tds.append(z)
    
    rows.append(tds)
rows

[['NorthAmerica',
  '131,889,132',
  '1,695,941',
  '127,665,129',
  '+350',
  '2,528,062',
  '6,095',
  'NorthAmerica'],
 ['Asia',
  '221,500,265',
  '1,553,662',
  '205,673,091',
  '14,273,512',
  '14,733',
  'Asia'],
 ['Europe',
  '253,406,198',
  '2,101,824',
  '248,754,104',
  '+474',
  '2,550,270',
  '4,453',
  'Europe'],
 ['SouthAmerica',
  '70,200,879',
  '1,367,332',
  '66,683,585',
  '2,149,962',
  '8,953',
  'SouthAmerica'],
 ['Oceania',
  '14,895,771',
  '33,015',
  '14,752,388',
  '110,368',
  '31',
  'Australia/Oceania'],
 ['Africa', '12,860,924', '258,892', '12,090,808', '511,224', '529', 'Africa'],
 ['721', '15', '706', '0', '0'],
 ['World',
  '704,753,890',
  '0',
  '7,010,681',
  '0',
  '675,619,811',
  '+790',
  '22,123,398',
  '34,794',
  '90,413',
  '899.4',
  'All'],
 ['1',
  'USA',
  '111,820,082',
  '1,219,487',
  '109,814,428',
  '786,167',
  '940',
  '333,985',
  '3,642',
  '1,186,851,502',
  '3,544,901',
  '334,805,269',
  'NorthAmerica',
  '3',
  '275',
  '0',
  '2,348'],
 ['2',
  'India',
  '45,035,393',
  '533,570',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '32,016',
  '379',
  '935,879,495',
  '665,334',
  '1,406,631,776',
  'Asia',
  '31',
  '2,636',
  '2',
  '0.4'],
 ['3',
  'France',
  '40,138,560',
  '167,642',
  '39,970,918',
  '0',
  '612,013',
  '2,556',
  '271,490,188',
  '4,139,547',
  '65,584,518',
  'Europe',
  '2',
  '391',
  '0'],
 ['4',
  'Germany',
  '38,828,995',
  '183,027',
  '38,240,600',
  '405,368',
  'N/A',
  '462,891',
  '2,182',
  '122,332,384',
  '1,458,359',
  '83,883,596',
  'Europe',
  '2',
  '458',
  '1',
  '4,833'],
 ['5',
  'Brazil',
  '38,743,918',
  '711,380',
  '36,249,161',
  '1,783,377',
  'N/A',
  '179,908',
  '3,303',
  '63,776,166',
  '296,146',
  '215,353,593',
  'SouthAmerica',
  '6',
  '303',
  '3',
  '8,281'],
 ['6',
  'S.Korea',
  '34,571,873',
  '35,934',
  '34,535,939',
  '0',
  '673,523',
  '700',
  '15,804,065',
  '307,892',
  '51,329,899',
  'Asia',
  '1',
  '1,428',
  '3'],
 ['7',
  'Japan',
  '33,803,572',
  '74,694',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '269,169',
  '595',
  '100,414,883',
  '799,578',
  '125,584,838',
  'Asia',
  '4',
  '1,681',
  '1',
  '95,582'],
 ['8',
  'Italy',
  '26,723,249',
  '196,487',
  '26,361,218',
  '165,544',
  '22',
  '443,445',
  '3,261',
  '281,126,449',
  '4,665,010',
  '60,262,770',
  'Europe',
  '2',
  '307',
  '0',
  '2,747'],
 ['9',
  'UK',
  '24,910,387',
  '232,112',
  '24,678,275',
  '0',
  'N/A',
  '363,666',
  '3,389',
  '522,526,476',
  '7,628,357',
  '68,497,907',
  'Europe',
  '3',
  '295',
  '0'],
 ['10',
  'Russia',
  '24,124,215',
  '402,756',
  '23,545,818',
  '175,641',
  'N/A',
  '165,454',
  '2,762',
  '273,400,000',
  '1,875,095',
  '145,805,947',
  'Europe',
  '6',
  '362',
  '1',
  '1,205'],
 ['11',
  'Turkey',
  '17,232,066',
  '102,174',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '201,399',
  '1,194',
  '162,743,369',
  '1,902,052',
  '85,561,976',
  'Asia',
  '5',
  '837',
  '1',
  '4,024'],
 ['12',
  'Spain',
  '13,914,811',
  '121,760',
  '13,762,417',
  '30,634',
  '231',
  '297,840',
  '2,606',
  '471,036,328',
  '10,082,298',
  '46,719,142',
  'Europe',
  '3',
  '384',
  '0',
  '656'],
 ['13',
  'Australia',
  '11,853,144',
  '24,414',
  '11,820,014',
  '8,716',
  '3',
  '454,687',
  '937',
  '81,916,639',
  '3,142,326',
  '26,068,792',
  'Australia/Oceania',
  '2',
  '1,068',
  '0',
  '334'],
 ['14',
  'Vietnam',
  '11,625,195',
  '43,206',
  '10,640,971',
  '941,018',
  '117,481',
  '437',
  '85,826,548',
  '867,342',
  '98,953,541',
  'Asia',
  '9',
  '2,290',
  '1',
  '9,510'],
 ['15',
  'Taiwan',
  '10,241,523',
  '19,005',
  '10,222,518',
  '0',
  '428,720',
  '796',
  '30,742,304',
  '1,286,903',
  '23,888,595',
  'Asia',
  '2',
  '1,257',
  '1'],
 ['16',
  'Argentina',
  '10,128,845',
  '130,841',
  '9,997,258',
  '746',
  '220,143',
  '2,844',
  '35,716,069',
  '776,264',
  '46,010,234',
  'SouthAmerica',
  '5',
  '352',
  '1',
  '16'],
 ['17',
  'Netherlands',
  '8,635,786',
  '22,992',
  '8,612,599',
  '195',
  'N/A',
  '501,747',
  '1,336',
  '25,984,435',
  '1,509,718',
  '17,211,447',
  'Europe',
  '2',
  '749',
  '1',
  '11'],
 ['18',
  'Mexico',
  '7,702,809',
  '334,958',
  '6,899,865',
  '467,986',
  'N/A',
  '58,549',
  '2,546',
  '20,013,810',
  '152,124',
  '131,562,772',
  'NorthAmerica',
  '17',
  '393',
  '7',
  '3,557'],
 ['19',
  'Iran',
  '7,627,186',
  '146,811',
  'N/A',
  'N/A',
  'N/A',
  '88,665',
  '1,707',
  '57,320,267',
  '666,338',
  '86,022,837',
  'Asia',
  '11',
  '586',
  '2',
  '1,199'],
 ['20',
  'Indonesia',
  '6,829,221',
  '162,063',
  '6,647,104',
  '20,054',
  'N/A',
  '24,466',
  '581',
  '114,158,919',
  '408,975',
  '279,134,505',
  'Asia',
  '41',
  '1,722',
  '2',
  '72'],
 ['21',
  'Poland',
  '6,661,991',
  '120,598',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '176,524',
  '3,196',
  '39,323,709',
  '1,041,970',
  '37,739,785',
  'Europe',
  '6',
  '313',
  '1',
  '31,941'],
 ['22',
  'Colombia',
  '6,400,173',
  '143,200',
  '6,212,152',
  '44,821',
  '342',
  '124,244',
  '2,780',
  '36,951,507',
  '717,327',
  '51,512,762',
  'SouthAmerica',
  '8',
  '360',
  '1',
  '870'],
 ['23',
  'Greece',
  '6,101,379',
  '37,869',
  'N/A',
  'N/A',
  'N/A',
  '591,412',
  '3,671',
  '102,228,365',
  '9,909,078',
  '10,316,637',
  'Europe',
  '2',
  '272',
  '0'],
 ['24',
  'Austria',
  '6,081,287',
  '22,542',
  '6,054,934',
  '3,811',
  '670,727',
  '2,486',
  '211,273,524',
  '23,302,116',
  '9,066,710',
  'Europe',
  '1',
  '402',
  '0',
  '420'],
 ['25',
  'Portugal',
  '5,643,062',
  '28,126',
  '5,614,809',
  '127',
  '61',
  '556,484',
  '2,774',
  '46,139,518',
  '4,549,993',
  '10,140,570',
  'Europe',
  '2',
  '361',
  '0',
  '13'],
 ['26',
  'Ukraine',
  '5,557,995',
  '112,418',
  '5,445,577',
  '0',
  '128,681',
  '2,603',
  '32,603,805',
  '754,855',
  '43,192,122',
  'Europe',
  '8',
  '384',
  '1'],
 ['27',
  'Chile',
  '5,384,853',
  '64,497',
  '5,252,450',
  '67,906',
  '7',
  '279,730',
  '3,350',
  '50,382,097',
  '2,617,225',
  '19,250,195',
  'SouthAmerica',
  '4',
  '298',
  '0',
  '3,528'],
 ['28',
  'Malaysia',
  '5,278,406',
  '37,348',
  '5,233,268',
  '7,790',
  '11',
  '159,079',
  '1,126',
  '68,580,916',
  '2,066,869',
  '33,181,072',
  'Asia',
  '6',
  '888',
  '0',
  '235'],
 ['29',
  'Canada',
  '4,946,090',
  '59,034',
  '4,881,312',
  '+350',
  '5,744',
  '99',
  '128,843',
  '1,538',
  '66,572,774',
  '1,734,189',
  '38,388,419',
  'NorthAmerica',
  '8',
  '650',
  '1',
  '150'],
 ['30',
  'Belgium',
  '4,861,695',
  '34,376',
  '4,826,798',
  '+50',
  '521',
  'N/A',
  '416,659',
  '2,946',
  '37,454,182',
  '3,209,915',
  '11,668,278',
  'Europe',
  '2',
  '339',
  '0',
  '45'],
 ['31',
  'Israel',
  '4,841,772',
  '12,707',
  '4,798,473',
  '30,592',
  'N/A',
  '519,169',
  '1,363',
  '41,373,364',
  '4,436,346',
  '9,326,000',
  'Asia',
  '2',
  '734',
  '0',
  '3,280'],
 ['32',
  'DPRK',
  '4,772,813',
  '74',
  '4,772,739',
  '0',
  '183,636',
  '3',
  '25,990,679',
  'Asia',
  '5',
  '351,225'],
 ['33',
  'Thailand',
  '4,770,149',
  '34,586',
  '4,692,636',
  '42,927',
  'N/A',
  '68,069',
  '494',
  '17,273,454',
  '246,488',
  '70,078,203',
  'Asia',
  '15',
  '2,026',
  '4',
  '613'],
 ['34',
  'Czechia',
  '4,759,041',
  '43,517',
  '4,715,206',
  '318',
  '2',
  '443,246',
  '4,053',
  '57,834,241',
  '5,386,552',
  '10,736,784',
  'Europe',
  '2',
  '247',
  '0',
  '30'],
 ['35',
  'Peru',
  '4,572,667',
  '222,161',
  '4,350,506',
  '0',
  '4',
  '135,751',
  '6,595',
  '39,010,194',
  '1,158,115',
  '33,684,208',
  'SouthAmerica',
  '7',
  '152',
  '1'],
 ['36',
  'Switzerland',
  '4,453,053',
  '14,452',
  '4,438,309',
  '292',
  'N/A',
  '507,549',
  '1,647',
  '23,833,472',
  '2,716,487',
  '8,773,637',
  'Europe',
  '2',
  '607',
  '0',
  '33'],
 ['37',
  'Philippines',
  '4,140,383',
  '66,864',
  '4,067,381',
  '6,138',
  'N/A',
  '36,800',
  '594',
  '36,102,746',
  '320,888',
  '112,508,994',
  'Asia',
  '27',
  '1,683',
  '3',
  '55'],
 ['38',
  'SouthAfrica',
  '4,076,463',
  '102,595',
  '3,912,506',
  '61,362',
  '192',
  '67,095',
  '1,689',
  '26,795,090',
  '441,027',
  '60,756,135',
  'Africa',
  '15',
  '592',
  '2',
  '1,010'],
 ['39',
  'Romania',
  '3,529,735',
  '68,929',
  '3,460,149',
  '+390',
  '657',
  '21',
  '185,470',
  '3,622',
  '28,758,667',
  '1,511,122',
  '19,031,335',
  'Europe',
  '5',
  '276',
  '1',
  '35'],
 ['40',
  'Denmark',
  '3,183,756',
  '8,814',
  '3,174,942',
  '0',
  '545,636',
  '1,511',
  '129,333,107',
  '22,165,247',
  '5,834,950',
  'Europe',
  '2',
  '662',
  '0'],
 ['41',
  'Singapore',
  '3,006,155',
  '2,024',
  '3,004,131',
  '0',
  '4',
  '505,785',
  '341',
  '24,756,666',
  '4,165,302',
  '5,943,546',
  'Asia',
  '2',
  '2,937',
  '0'],
 ['42',
  'HongKong',
  '2,937,609',
  '14,924',
  '2,916,005',
  '6,680',
  'N/A',
  '386,309',
  '1,963',
  '76,127,725',
  '10,011,143',
  '7,604,299',
  'Asia',
  '3',
  '510',
  '0',
  '878'],
 ['43',
  'Sweden',
  '2,754,129',
  '27,407',
  '2,726,492',
  '+20',
  '230',
  'N/A',
  '269,511',
  '2,682',
  '19,500,873',
  '1,908,301',
  '10,218,971',
  'Europe',
  '4',
  '373',
  '1',
  '23'],
 ['44',
  'NewZealand',
  '2,621,111',
  '5,697',
  '2,613,791',
  '1,623',
  '535,117',
  '1,163',
  '7,768,604',
  '1,586,011',
  '4,898,203',
  'Australia/Oceania',
  '2',
  '860',
  '1',
  '331'],
 ['45',
  'Serbia',
  '2,615,054',
  '18,057',
  '2,596,608',
  '389',
  '302,213',
  '2,087',
  '13,463,733',
  '1,555,958',
  '8,653,016',
  'Europe',
  '3',
  '479',
  '1',
  '45'],
 ['46',
  'Iraq',
  '2,465,545',
  '25,375',
  '2,439,497',
  '673',
  '58,474',
  '602',
  '19,544,451',
  '463,523',
  '42,164,965',
  'Asia',
  '17',
  '1,662',
  '2',
  '16'],
 ['47',
  'Hungary',
  '2,230,232',
  '49,048',
  '2,152,155',
  '29,029',
  '232,164',
  '5,106',
  '11,394,556',
  '1,186,160',
  '9,606,259',
  'Europe',
  '4',
  '196',
  '1',
  '3,022'],
 ['48',
  'Bangladesh',
  '2,049,377',
  '29,493',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '12,207',
  '176',
  '15,254,399',
  '90,862',
  '167,885,689',
  'Asia',
  '82',
  '5,692',
  '11',
  '-168.58'],
 ['49',
  'Slovakia',
  '1,877,605',
  '21,224',
  '1,856,381',
  '0',
  '23',
  '343,872',
  '3,887',
  '7,448,789',
  '1,364,199',
  '5,460,193',
  'Europe',
  '3',
  '257',
  '1'],
 ['50',
  'Georgia',
  '1,861,665',
  '17,132',
  'N/A',
  'N/A',
  'N/A',
  '469,082',
  '4,317',
  '16,920,079',
  '4,263,340',
  '3,968,738',
  'Asia',
  '2',
  '232',
  '0',
  '17,130'],
 ['51',
  'Jordan',
  '1,746,997',
  '14,122',
  '1,731,007',
  '1,868',
  '59',
  '169,597',
  '1,371',
  '17,201,885',
  '1,669,945',
  '10,300,869',
  'Asia',
  '6',
  '729',
  '1',
  '181'],
 ['52',
  'Ireland',
  '1,734,582',
  '9,491',
  '1,724,921',
  '170',
  '19',
  '345,521',
  '1,891',
  '13,083,449',
  '2,606,161',
  '5,020,199',
  'Europe',
  '3',
  '529',
  '0',
  '34'],
 ['53',
  'Pakistan',
  '1,581,936',
  '30,664',
  '1,538,689',
  '12,583',
  '6,893',
  '134',
  '30,589,153',
  '133,292',
  '229,488,994',
  'Asia',
  '145',
  '7,484',
  '8',
  '55'],
 ['54',
  'Finland',
  '1,516,117',
  '11,958',
  '1,503,989',
  '+14',
  '170',
  'N/A',
  '272,930',
  '2,153',
  '12,108,977',
  '2,179,850',
  '5,554,960',
  'Europe',
  '4',
  '465',
  '0',
  '31'],
 ['55',
  'Norway',
  '1,509,732',
  '6,638',
  '1,503,094',
  '0',
  'N/A',
  '273,930',
  '1,204',
  '11,002,430',
  '1,996,315',
  '5,511,370',
  'Europe',
  '4',
  '830',
  '1'],
 ['56',
  'Kazakhstan',
  '1,411,831',
  '13,848',
  '1,383,020',
  '14,963',
  '24',
  '73,514',
  '721',
  '11,575,012',
  '602,707',
  '19,205,043',
  'Asia',
  '14',
  '1,387',
  '2',
  '779'],
 ['57',
  'Lithuania',
  '1,397,806',
  '9,897',
  '1,387,478',
  '431',
  'N/A',
  '525,154',
  '3,718',
  '10,540,357',
  '3,959,997',
  '2,661,708',
  'Europe',
  '2',
  '269',
  '0',
  '162'],
 ['58',
  'Slovenia',
  '1,356,546',
  '7,100',
  '1,349,424',
  '22',
  'N/A',
  '652,803',
  '3,417',
  '2,847,701',
  '1,370,382',
  '2,078,034',
  'Europe',
  '2',
  '293',
  '1',
  '11'],
 ['59',
  'Bulgaria',
  '1,339,851',
  '38,748',
  '1,292,944',
  '8,159',
  '22',
  '195,753',
  '5,661',
  '11,671,043',
  '1,705,147',
  '6,844,597',
  'Europe',
  '5',
  '177',
  '1',
  '1,192'],
 ['60',
  'Croatia',
  '1,309,728',
  '18,687',
  '1,258,432',
  '32,609',
  '322,650',
  '4,604',
  '5,660,084',
  '1,394,355',
  '4,059,286',
  'Europe',
  '3',
  '217',
  '1',
  '8,033'],
 ['61',
  'Guatemala',
  '1,291,293',
  '20,289',
  '1,269,891',
  '1,113',
  '5',
  '69,484',
  '1,092',
  '7,593,848',
  '408,622',
  '18,584,039',
  'NorthAmerica',
  '14',
  '916',
  '2',
  '60'],
 ['62',
  'Morocco',
  '1,278,992',
  '16,303',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '33,860',
  '432',
  '13,001,033',
  '344,191',
  '37,772,756',
  'Africa',
  '30',
  '2,317',
  '3',
  '173'],
 ['63',
  'Lebanon',
  '1,243,838',
  '10,952',
  '1,087,587',
  '145,299',
  '74',
  '186,068',
  '1,638',
  '4,795,578',
  '717,380',
  '6,684,849',
  'Asia',
  '5',
  '610',
  '1',
  '21,736'],
 ['64',
  'CostaRica',
  '1,238,883',
  '9,428',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '239,058',
  '1,819',
  '4,659,757',
  '899,158',
  '5,182,354',
  'NorthAmerica',
  '4',
  '550',
  '1',
  '71,154'],
 ['65',
  'Bolivia',
  '1,212,131',
  '22,407',
  '1,177,145',
  '12,579',
  '220',
  '101,073',
  '1,868',
  '2,710,261',
  '225,993',
  '11,992,656',
  'SouthAmerica',
  '10',
  '535',
  '4',
  '1,049'],
 ['66',
  'Tunisia',
  '1,153,361',
  '29,423',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '95,741',
  '2,442',
  '5,013,383',
  '416,164',
  '12,046,656',
  'Africa',
  '10',
  '409',
  '2',
  '1,157'],
 ['67',
  'Cuba',
  '1,115,251',
  '8,530',
  '1,106,660',
  '61',
  '98,645',
  '754',
  '14,402,674',
  '1,273,936',
  '11,305,652',
  'NorthAmerica',
  '10',
  '1,325',
  '1',
  '5'],
 ['68',
  'Ecuador',
  '1,070,188',
  '36,043',
  '1,034,145',
  '0',
  '59,083',
  '1,990',
  '3,082,403',
  '170,173',
  '18,113,361',
  'SouthAmerica',
  '17',
  '503',
  '6'],
 ['69',
  'UAE',
  '1,067,030',
  '2,349',
  'N/A',
  'N/A',
  'N/A',
  '105,837',
  '233',
  '200,732,262',
  '19,910,389',
  '10,081,785',
  'Asia',
  '9',
  '4,292',
  '0',
  '1,007'],
 ['70',
  'Panama',
  '1,059,893',
  '8,727',
  '1,051,102',
  '64',
  '16',
  '238,341',
  '1,962',
  '7,882,622',
  '1,772,585',
  '4,446,964',
  'NorthAmerica',
  '4',
  '510',
  '1',
  '14'],
 ['71',
  'Uruguay',
  '1,041,111',
  '7,664',
  '1,030,944',
  '2,503',
  '18',
  '297,799',
  '2,192',
  '6,114,822',
  '1,749,083',
  '3,496,016',
  'SouthAmerica',
  '3',
  '456',
  '1',
  '716'],
 ['72',
  'Mongolia',
  '1,011,496',
  '2,284',
  '1,009,212',
  '0',
  'N/A',
  '299,429',
  '676',
  '4,030,048',
  '1,193,000',
  '3,378,078',
  'Asia',
  '3',
  '1,479',
  '1'],
 ['73',
  'Nepal',
  '1,003,450',
  '12,031',
  '991,322',
  '97',
  '33,199',
  '398',
  '6,047,766',
  '200,088',
  '30,225,582',
  'Asia',
  '30',
  '2,512',
  '5',
  '3'],
 ['74',
  'Belarus',
  '994,037',
  '7,118',
  '985,592',
  '1,327',
  '105,381',
  '755',
  '13,646,641',
  '1,446,722',
  '9,432,800',
  'Europe',
  '9',
  '1,325',
  '1',
  '141'],
 ['75',
  'Latvia',
  '982,505',
  '6,715',
  '971,406',
  '4,384',
  '531,418',
  '3,632',
  '7,885,792',
  '4,265,272',
  '1,848,837',
  'Europe',
  '2',
  '275',
  '0',
  '2,371'],
 ['76',
  'SaudiArabia',
  '841,469',
  '9,646',
  'N/A',
  'N/A',
  'N/A',
  '23,475',
  '269',
  '45,481,735',
  '1,268,848',
  '35,844,909',
  'Asia',
  '43',
  '3,716',
  '1',
  '109'],
 ['77',
  'Paraguay',
  '837,602',
  '20,155',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '114,648',
  '2,759',
  '2,657,506',
  '363,751',
  '7,305,843',
  'SouthAmerica',
  '9',
  '362',
  '3',
  '16,306'],
 ['78',
  'Azerbaijan',
  '835,234',
  '10,400',
  '824,089',
  '745',
  '81,089',
  '1,010',
  '7,748,050',
  '752,223',
  '10,300,205',
  'Asia',
  '12',
  '990',
  '1',
  '72'],
 ['79',
  'Bahrain',
  '729,549',
  '1,574',
  '727,915',
  '60',
  'N/A',
  '408,944',
  '882',
  '10,948,549',
  '6,137,138',
  '1,783,983',
  'Asia',
  '2',
  '1,133',
  '0',
  '34'],
 ['80',
  'Cyprus',
  '681,110',
  '1,365',
  '679,745',
  '0',
  '556,741',
  '1,116',
  '9,640,118',
  '7,879,860',
  '1,223,387',
  'Asia',
  '2',
  '896',
  '0'],
 ['81',
  'DominicanRepublic',
  '675,890',
  '4,384',
  '671,316',
  '190',
  '4',
  '61,131',
  '397',
  '3,740,928',
  '338,350',
  '11,056,370',
  'NorthAmerica',
  '16',
  '2,522',
  '3',
  '17'],
 ['82',
  'SriLanka',
  '672,754',
  '16,897',
  '655,852',
  '5',
  '31,181',
  '783',
  '6,486,117',
  '300,619',
  '21,575,842',
  'Asia',
  '32',
  '1,277',
  '3',
  '0.2'],
 ['83',
  'Kuwait',
  '667,158',
  '2,570',
  'N/A',
  'N/A',
  'N/A',
  '152,308',
  '587',
  '8,455,743',
  '1,930,391',
  '4,380,326',
  'Asia',
  '7',
  '1,704',
  '1',
  '993'],
 ['84',
  'Myanmar',
  '641,873',
  '19,495',
  '620,159',
  '2,219',
  '11,622',
  '353',
  '11,711,514',
  '212,061',
  '55,227,143',
  'Asia',
  '86',
  '2,833',
  '5',
  '40'],
 ['85',
  'Moldova',
  '635,145',
  '12,218',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '158,265',
  '3,044',
  '3,216,305',
  '801,437',
  '4,013,171',
  'Europe',
  '6',
  '328',
  '1',
  '29,599'],
 ['86',
  'Estonia',
  '628,070',
  '3,001',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '475,123',
  '2,270',
  '6,968,103',
  '5,271,239',
  '1,321,910',
  'Europe',
  '2',
  '440',
  '0',
  '75,708'],
 ['87',
  'Palestine',
  '621,008',
  '5,404',
  '615,445',
  '159',
  '116,173',
  '1,011',
  '3,078,533',
  '575,907',
  '5,345,541',
  'Asia',
  '9',
  '989',
  '2',
  '30'],
 ['88',
  'Venezuela',
  '552,695',
  '5,856',
  '546,537',
  '302',
  '31',
  '18,885',
  '200',
  '3,359,014',
  '114,771',
  '29,266,991',
  'SouthAmerica',
  '53',
  '4,998',
  '9',
  '10'],
 ['89',
  'Egypt',
  '516,023',
  '24,613',
  '442,182',
  '49,228',
  '122',
  '4,861',
  '232',
  '3,693,367',
  '34,792',
  '106,156,692',
  'Africa',
  '206',
  '4,313',
  '29',
  '464'],
 ['90',
  'Qatar',
  '514,524',
  '690',
  '513,687',
  '147',
  '16',
  '172,664',
  '232',
  '4,065,369',
  '1,364,257',
  '2,979,915',
  'Asia',
  '6',
  '4,319',
  '1',
  '49'],
 ['91',
  'Libya',
  '507,274',
  '6,437',
  '500,835',
  '2',
  '72,048',
  '914',
  '2,483,848',
  '352,782',
  '7,040,745',
  'Africa',
  '14',
  '1,094',
  '3',
  '0.3'],
 ['92',
  'Ethiopia',
  '501,157',
  '7,574',
  '488,171',
  '5,412',
  '4,148',
  '63',
  '5,565,340',
  '46,066',
  '120,812,698',
  'Africa',
  '241',
  '15,951',
  '22',
  '45'],
 ['93',
  'RÃ©union',
  '494,595',
  '921',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '544,672',
  '1,014',
  '1,603,660',
  '1,766,027',
  '908,061',
  'Africa',
  '2',
  '986',
  '1',
  '82,706'],
 ['94',
  'Honduras',
  '474,590',
  '11,165',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '46,432',
  '1,092',
  '1,660,662',
  '162,472',
  '10,221,247',
  'NorthAmerica',
  '22',
  '915',
  '6',
  '32,372'],
 ['95',
  'Armenia',
  '451,831',
  '8,777',
  '435,162',
  '7,892',
  '152,031',
  '2,953',
  '3,242,901',
  '1,091,164',
  '2,971,966',
  'Asia',
  '7',
  '339',
  '1',
  '2,655'],
 ['96',
  'BosniaandHerzegovina',
  '403,615',
  '16,388',
  '379,084',
  '8,143',
  '124,215',
  '5,044',
  '1,884,721',
  '580,036',
  '3,249,317',
  'Europe',
  '8',
  '198',
  '2',
  '2,506'],
 ['97',
  'Oman',
  '399,449',
  '4,628',
  'N/A',
  'N/A',
  'N/A',
  '75,028',
  '869',
  '25,000,000',
  '4,695,724',
  '5,323,993',
  'Asia',
  '13',
  '1,150',
  '0',
  '1,907'],
 ['98',
  'Luxembourg',
  '391,232',
  '1,232',
  'N/A',
  'N/A',
  'N/A',
  '609,044',
  '1,918',
  '4,587,145',
  '7,140,959',
  '642,371',
  'Europe',
  '2',
  '521',
  '0',
  '114,124'],
 ['99',
  'NorthMacedonia',
  '350,567',
  '9,976',
  '337,068',
  '3,523',
  '168,436',
  '4,793',
  '2,226,216',
  '1,069,626',
  '2,081,304',
  'Europe',
  '6',
  '209',
  '1',
  '1,693'],
 ['100',
  'Zambia',
  '349,304',
  '4,069',
  '341,316',
  '3,919',
  '17,940',
  '209',
  '4,112,961',

In [16]:
header = tr_code[0].text.split('\n')[1:-1]
rows = [row[:len(header)] + [""] * (len(header) - len(row)) for row in rows]

In [17]:
import pandas as pd

df = pd.DataFrame(rows,columns = header)
df

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,TotalTests,Tests/,1M pop,,Population,Continent,1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
0,NorthAmerica,"131,889,132","1,695,941","127,665,129",+350,"2,528,062","6,095",NorthAmerica,,,...,,,,,,,,,,
1,Asia,"221,500,265","1,553,662","205,673,091","14,273,512","14,733",Asia,,,,...,,,,,,,,,,
2,Europe,"253,406,198","2,101,824","248,754,104",+474,"2,550,270","4,453",Europe,,,...,,,,,,,,,,
3,SouthAmerica,"70,200,879","1,367,332","66,683,585","2,149,962","8,953",SouthAmerica,,,,...,,,,,,,,,,
4,Oceania,"14,895,771","33,015","14,752,388","110,368",31,Australia/Oceania,,,,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,Total:,"70,200,879","1,367,332","66,683,585","2,149,962","8,953",SouthAmerica,,,,...,,,,,,,,,,
243,Total:,"14,895,771","33,015","14,752,388","110,368",31,Australia/Oceania,,,,...,,,,,,,,,,
244,Total:,"12,860,924","258,892","12,090,808","511,224",529,Africa,,,,...,,,,,,,,,,
245,Total:,721,15,706,0,0,,,,,...,,,,,,,,,,
246,Total:,"704,753,890",0,"7,010,681",0,"675,619,811",+790,"22,123,398","34,794","90,413.4",...,,,,,,,,,,

In [18]:
df.to_csv('worldometer_data.csv')

In [19]:
df['TotalCases'] = [float(i.replace(',','')) for i in df['TotalCases']]

In [20]:
df1 = df

In [28]:
df1 = df.sort_values(by=['TotalCases'], ascending = False).iloc[0:10]
df1

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,TotalTests,Tests/,1M pop,,Population,Continent,1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
8,1,USA,111820082.0,"1,219,487","109,814,428","786,167",940,"333,985","3,642","1,186,851,502",...,NorthAmerica,3,275,0,"2,348",,,,,
9,2,India,45035393.0,"533,570",N/A,N/A,N/A,N/A,"32,016",379,...,"1,406,631,776",Asia,31,"2,636",2,0.4,,,,
10,3,France,40138560.0,"167,642","39,970,918",0,"612,013","2,556","271,490,188","4,139,547",...,2,391,0,,,,,,,
11,4,Germany,38828995.0,"183,027","38,240,600","405,368",N/A,"462,891","2,182","122,332,384",...,Europe,2,458,1,"4,833",,,,,
12,5,Brazil,38743918.0,"711,380","36,249,161","1,783,377",N/A,"179,908","3,303","63,776,166",...,SouthAmerica,6,303,3,"8,281",,,,,
13,6,S.Korea,34571873.0,"35,934","34,535,939",0,"673,523",700,"15,804,065","307,892",...,1,"1,428",3,,,,,,,
14,7,Japan,33803572.0,"74,694",N/A,N/A,N/A,N/A,"269,169",595,...,"125,584,838",Asia,4,"1,681",1,"95,582",,,,
15,8,Italy,26723249.0,"196,487","26,361,218","165,544",22,"443,445","3,261","281,126,449",...,Europe,2,307,0,"2,747",,,,,
16,9,UK,24910387.0,"232,112","24,678,275",0,N/A,"363,666","3,389","522,526,476",...,Europe,3,295,0,,,,,,
17,10,Russia,24124215.0,"402,756","23,545,818","175,641",N/A,"165,454","2,762","273,400,000",...,Europe,6,362,1,"1,205",,,,,

In [29]:
df1

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,TotalTests,Tests/,1M pop,,Population,Continent,1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
8,1,USA,111820082.0,"1,219,487","109,814,428","786,167",940,"333,985","3,642","1,186,851,502",...,NorthAmerica,3,275,0,"2,348",,,,,
9,2,India,45035393.0,"533,570",N/A,N/A,N/A,N/A,"32,016",379,...,"1,406,631,776",Asia,31,"2,636",2,0.4,,,,
10,3,France,40138560.0,"167,642","39,970,918",0,"612,013","2,556","271,490,188","4,139,547",...,2,391,0,,,,,,,
11,4,Germany,38828995.0,"183,027","38,240,600","405,368",N/A,"462,891","2,182","122,332,384",...,Europe,2,458,1,"4,833",,,,,
12,5,Brazil,38743918.0,"711,380","36,249,161","1,783,377",N/A,"179,908","3,303","63,776,166",...,SouthAmerica,6,303,3,"8,281",,,,,
13,6,S.Korea,34571873.0,"35,934","34,535,939",0,"673,523",700,"15,804,065","307,892",...,1,"1,428",3,,,,,,,
14,7,Japan,33803572.0,"74,694",N/A,N/A,N/A,N/A,"269,169",595,...,"125,584,838",Asia,4,"1,681",1,"95,582",,,,
15,8,Italy,26723249.0,"196,487","26,361,218","165,544",22,"443,445","3,261","281,126,449",...,Europe,2,307,0,"2,747",,,,,
16,9,UK,24910387.0,"232,112","24,678,275",0,N/A,"363,666","3,389","522,526,476",...,Europe,3,295,0,,,,,,
17,10,Russia,24124215.0,"402,756","23,545,818","175,641",N/A,"165,454","2,762","273,400,000",...,Europe,6,362,1,"1,205",,,,,

In [30]:
import plotly.express as px

fig = px.bar(df1, x='Country,Other', y='TotalCases')
fig.show()

In [31]:
df1['ActiveCases'] = [float(i.replace(',','')) for i in df1['ActiveCases']]
df1['Serious,Critical'] = [float(i.replace(',','')) for i in df1['Serious,Critical']]

In [32]:
df1

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,TotalTests,Tests/,1M pop,,Population,Continent,1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
8,1,USA,111820082.0,"1,219,487","109,814,428","786,167",940,"333,985",3642.0,1.186852e+09,...,NorthAmerica,3,275,0,"2,348",,,,,
9,2,India,45035393.0,"533,570",N/A,N/A,N/A,N/A,32016.0,3.790000e+02,...,"1,406,631,776",Asia,31,"2,636",2,0.4,,,,
10,3,France,40138560.0,"167,642","39,970,918",0,"612,013","2,556",271490188.0,4.139547e+06,...,2,391,0,,,,,,,
11,4,Germany,38828995.0,"183,027","38,240,600","405,368",N/A,"462,891",2182.0,1.223324e+08,...,Europe,2,458,1,"4,833",,,,,
12,5,Brazil,38743918.0,"711,380","36,249,161","1,783,377",N/A,"179,908",3303.0,6.377617e+07,...,SouthAmerica,6,303,3,"8,281",,,,,
13,6,S.Korea,34571873.0,"35,934","34,535,939",0,"673,523",700,15804065.0,3.078920e+05,...,1,"1,428",3,,,,,,,
14,7,Japan,33803572.0,"74,694",N/A,N/A,N/A,N/A,269169.0,5.950000e+02,...,"125,584,838",Asia,4,"1,681",1,"95,582",,,,
15,8,Italy,26723249.0,"196,487","26,361,218","165,544",22,"443,445",3261.0,2.811264e+08,...,Europe,2,307,0,"2,747",,,,,
16,9,UK,24910387.0,"232,112","24,678,275",0,N/A,"363,666",3389.0,5.225265e+08,...,Europe,3,295,0,,,,,,
17,10,Russia,24124215.0,"402,756","23,545,818","175,641",N/A,"165,454",2762.0,2.734000e+08,...,Europe,6,362,1,"1,205",,,,,

In [33]:
import plotly.graph_objects as go


fig = go.Figure(data=[
    go.Bar(name='Active Cases', x=df1['Country,Other'], y=df1['ActiveCases']),
    go.Bar(name='Serious or Critical', x=df1['Country,Other'], y=df1['Serious,Critical'])
])
fig.update_layout(barmode='group')
fig.show()